// Catalogo padrao do Impérium.
//
// Este arquivo e a SEMENTE do jogo: garante que o mundo seja jogavel mesmo
// antes (ou sem) o administrador cadastrar conteudo no painel. O que o admin
// cria no Firestore tem precedencia sobre estes valores.

export const ITENS_SEMENTE = [
  // ---------- recursos de extracao ----------
  {
    id: 'terra',
    nome: 'Terra Fértil',
    descricao: 'Terra fertil revistada de humus. Base de qualquer alicerce e materia-prima de quase toda transformacao.',
    tipo: 'bloco',
    uso: ['extracao', 'transformacao', 'estrutura'],
    raridade: 'comum',
    cor: 0x6b4a2b,
    textura: 'bloco',
    resistMineracao: 1,
    valor: 1,
    stackMax: 999,
    nivelMin: 1,
    slotsUpgrade: 3,
  },
  {
    id: 'pedra',
    nome: 'Pedra Rústica',
    descricao: 'Pedra rustica arrancada do leito rochoso. Cara, heavy e indispensavel: e a moeda do Imperio.',
    tipo: 'bloco',
    uso: ['extracao', 'transformacao', 'estrutura'],
    raridade: 'comum',
    cor: 0x8a8a8a,
    textura: 'bloco',
    resistMineracao: 2,
    valor: 2,
    stackMax: 999,
    nivelMin: 1,
    slotsUpgrade: 3,
  },
  {
    id: 'madeira',
    nome: 'Madeira de Carvalho',
    descricao: 'Madeira de carvalho de corte lento. Serve de estrutura, de combustivel e, trabalhada, de ferramenta.',
    tipo: 'bloco',
    uso: ['extracao', 'transformacao', 'estrutura', 'equipavel'],
    raridade: 'comum',
    cor: 0x8a5a2b,
    textura: 'bloco',
    resistMineracao: 1,
    valor: 3,
    stackMax: 999,
    nivelMin: 1,
    slotsUpgrade: 3,
  },
  {
    id: 'minerio_ferro',
    nome: 'Minério de Ferro',
    descricao: 'Minerio de ferro bruto. Precisa de fundicao na Forja antes de virar ferramenta ou armadura.',
    tipo: 'recurso',
    uso: ['extracao', 'transformacao'],
    raridade: 'comum',
    cor: 0xb06a3a,
    textura: 'bloco',
    resistMineracao: 3,
    valor: 6,
    stackMax: 999,
    nivelMin: 1,
    slotsUpgrade: 3,
  },
  {
    id: 'minerio_ouro',
    nome: 'Minério de Ouro',
    descricao: 'Veios de ouro entre a pedra. Fonte de riqueza, mas exige mineracao de alto nivel e afiada.',
    tipo: 'recurso',
    uso: ['extracao', 'transformacao'],
    raridade: 'incomum',
    cor: 0xe0b64a,
    textura: 'bloco',
    resistMineracao: 4,
    valor: 18,
    stackMax: 999,
    nivelMin: 3,
    slotsUpgrade: 3,
  },
  {
    id: 'cristal_arcano',
    nome: 'Cristal Arcano',
    descricao: 'Cristal bruto impregnado de mana. As maquinas de nivel alto e o vidro arcano nascem daqui.',
    tipo: 'recurso',
    uso: ['extracao', 'transformacao', 'maquina'],
    raridade: 'raro',
    cor: 0x9a6fe0,
    textura: 'bloco',
    resistMineracao: 6,
    valor: 55,
    stackMax: 999,
    nivelMin: 6,
    slotsUpgrade: 4,
  },
  {
    id: 'essencia_eterea',
    nome: 'Essência Etérea',
    descricao: 'Essencia condensada de um Reino Etereo. Rara, volatil e cara demais para ser descartada.',
    tipo: 'recurso',
    uso: ['extracao', 'transformacao'],
    raridade: 'epico',
    cor: 0x6fd8e0,
    textura: 'particula',
    resistMineracao: 8,
    valor: 160,
    stackMax: 999,
    nivelMin: 12,
    slotsUpgrade: 4,
  },

  // ---------- blocos construidos ----------
  {
    id: 'bloco_pedra_reforcada',
    nome: 'Bloco de Pedra Reforçada',
    descricao: 'Bloco de pedra calcada com residuo de mana. Dura muito mais que a pedra bruta.',
    tipo: 'estrutura',
    uso: ['estrutura'],
    raridade: 'comum',
    cor: 0x6e6e6e,
    textura: 'bloco',
    vidaBloco: 220,
    valor: 12,
    stackMax: 999,
    nivelMin: 1,
    slotsUpgrade: 4,
  },
  {
    id: 'bloco_madeira_tratada',
    nome: 'Bloco de Madeira Tratada',
    descricao: 'Tabuas seladas com resina. Sustentam estruturas altas sem apodrecer.',
    tipo: 'estrutura',
    uso: ['estrutura'],
    raridade: 'comum',
    cor: 0x7a4a22,
    textura: 'bloco',
    vidaBloco: 160,
    valor: 10,
    stackMax: 999,
    nivelMin: 1,
    slotsUpgrade: 4,
  },
  {
    id: 'bloco_vidro_arcano',
    nome: 'Bloco de Vidro Arcano',
    descricao: 'Painel de vidro lapidado com runas. Deixa passar a luz do Portal e serve de janela ritual.',
    tipo: 'estrutura',
    uso: ['estrutura', 'utilizacao'],
    raridade: 'raro',
    cor: 0x8ab4d8,
    textura: 'bloco',
    vidaBloco: 140,
    valor: 40,
    stackMax: 999,
    nivelMin: 6,
    slotsUpgrade: 4,
  },
  {
    id: 'bloco_runico',
    nome: 'Bloco Rúnico',
    descricao: 'Bloco entalhado com o selo dos reinos. Essencial para Portais Arcanos e prensas de alta potencia.',
    tipo: 'estrutura',
    uso: ['estrutura', 'maquina'],
    raridade: 'epico',
    cor: 0x7a4fd4,
    textura: 'bloco',
    vidaBloco: 400,
    valor: 180,
    stackMax: 999,
    nivelMin: 14,
    slotsUpgrade: 5,
  },

  // ---------- ferramentas ----------
  {
    id: 'picareta_ferro',
    nome: 'Picareta de Ferro',
    descricao: 'Picareta de ferro temperado. O primeiro salto de produtividade na mineracao.',
    tipo: 'ferramenta',
    uso: ['utilizacao', 'equipavel'],
    raridade: 'comum',
    cor: 0xb06a3a,
    textura: 'ferramenta',
    poderMineracao: 4,
    ferramentas: ['picareta'],
    nivelMin: 2,
    stackMax: 1,
  },
  {
    id: 'machado_aco',
    nome: 'Machado de Aço',
    descricao: 'Machado de aco de lamina larga. Extrai madeira muito mais rapido que a mao nua.',
    tipo: 'ferramenta',
    uso: ['utilizacao', 'equipavel'],
    raridade: 'incomum',
    cor: 0xc0c8d0,
    textura: 'ferramenta',
    poderMineracao: 5,
    ferramentas: ['machado'],
    nivelMin: 4,
    stackMax: 1,
  },
  {
    id: 'picareta_runic',
    nome: 'Picareta Rúnica',
    descricao: 'Picareta lapidada em cristal arcano. Perde-se entre os cristais e na rocha viva.',
    tipo: 'ferramenta',
    uso: ['utilizacao', 'equipavel'],
    raridade: 'lendario',
    cor: 0xc9a6ff,
    textura: 'ferramenta',
    poderMineracao: 14,
    ferramentas: ['picareta'],
    nivelMin: 18,
    stackMax: 1,
  },

  // ---------- equipaveis ----------
  {
    id: 'armadura_couro',
    nome: 'Armadura de Couro',
    descricao: 'Giba de couro curtido. Barata e suficiente para nao morrer no primeiro slime.',
    tipo: 'equipavel',
    uso: ['equipavel'],
    raridade: 'comum',
    cor: 0x7a4a22,
    textura: 'equipavel',
    slot: 'corpo',
    defesa: 6,
    vidaMax: 20,
    nivelMin: 3,
    stackMax: 1,
    slotsUpgrade: 4,
  },
  {
    id: 'armadura_placas',
    nome: 'Armadura de Placas',
    descricao: 'Placas de metal cravadas sobre couro. Protege de verdade contra o que vier do submundo.',
    tipo: 'equipavel',
    uso: ['equipavel'],
    raridade: 'raro',
    cor: 0x9a9a9a,
    textura: 'equipavel',
    slot: 'corpo',
    defesa: 18,
    vidaMax: 60,
    fis: 3,
    nivelMin: 10,
    stackMax: 1,
    slotsUpgrade: 5,
  },
  {
    id: 'anel_arcano',
    nome: 'Anel Arcano',
    descricao: 'Anel gravado com um selo de mana. Ampara os dedos com um fio de poder.',
    tipo: 'equipavel',
    uso: ['equipavel'],
    raridade: 'epico',
    cor: 0x9a6fe0,
    textura: 'equipavel',
    slot: 'anel',
    poderMax: 40,
    men: 6,
    nivelMin: 14,
    stackMax: 1,
    slotsUpgrade: 5,
  },

  // ---------- maquinas ----------
  {
    id: 'estacao_forja',
    nome: 'Forja Imperial',
    descricao: 'Forja acesa com brasa permanente. Funde minerio em lingotes e molda ferramentas.',
    tipo: 'maquina',
    uso: ['maquina', 'estrutura'],
    raridade: 'comum',
    cor: 0x6b4a2b,
    textura: 'maquina',
    estacao: 'forja',
    vidaBloco: 320,
    nivelMin: 3,
    stackMax: 1,
    slotsUpgrade: 4,
  },
  {
    id: 'estacao_alquimia',
    nome: 'Mesa Alquímica',
    descricao: 'Mesa com caldeiras e frascos. Transforma essencias em pocoes e catalisadores.',
    tipo: 'maquina',
    uso: ['maquina', 'estrutura'],
    raridade: 'comum',
    cor: 0x4a6b5a,
    textura: 'maquina',
    estacao: 'alquimia',
    vidaBloco: 260,
    nivelMin: 5,
    stackMax: 1,
    slotsUpgrade: 4,
  },
  {
    id: 'estacao_torno',
    nome: 'Torno Rúnico',
    descricao: 'Torno movido a cristais. Depende de maquinas anteriores, mas multiplica a producao.',
    tipo: 'maquina',
    uso: ['maquina'],
    raridade: 'incomum',
    cor: 0x7a4fd4,
    textura: 'maquina',
    estacao: 'torno',
    vidaBloco: 300,
    nivelMin: 8,
    stackMax: 1,
    slotsUpgrade: 4,
  },
  {
    id: 'prensa_arcana',
    nome: 'Prensa Arcana',
    descricao: 'Prensa que compacta energia sob pressao. Produz os Orbes Arcanos de alto nivel.',
    tipo: 'maquina',
    uso: ['maquina'],
    raridade: 'epico',
    cor: 0xc9a6ff,
    textura: 'maquina',
    estacao: 'prensa_arcana',
    vidaBloco: 420,
    nivelMin: 16,
    stackMax: 1,
    slotsUpgrade: 5,
  },

  // ---------- orbes ----------
  {
    id: 'orbe_arcano_menor',
    nome: 'Orbe Arcano Menor',
    descricao: 'Orbe de energia menor. Eleva um item do nivel 1 ao 10.',
    tipo: 'orbe',
    uso: ['utilizacao'],
    raridade: 'comum',
    cor: 0xd4af6a,
    textura: 'orbe',
    faixa: { min: 1, max: 10 },
    valor: 120,
    stackMax: 999,
  },
  {
    id: 'orbe_arcano_medio',
    nome: 'Orbe Arcano Médio',
    descricao: 'Orbe medio, mais denso. Leva um item do nivel 11 ao 25.',
    tipo: 'orbe',
    uso: ['utilizacao'],
    raridade: 'incomum',
    cor: 0x7ad4a0,
    textura: 'orbe',
    faixa: { min: 11, max: 25 },
    valor: 900,
    stackMax: 999,
  },
  {
    id: 'orbe_arcano_superior',
    nome: 'Orbe Arcano Superior',
    descricao: 'Orbe superior. Concentrado o bastante para levar um item do nivel 26 ao 40.',
    tipo: 'orbe',
    uso: ['utilizacao'],
    raridade: 'raro',
    cor: 0x7ab4d8,
    textura: 'orbe',
    faixa: { min: 26, max: 40 },
    valor: 8000,
    stackMax: 999,
  },
  {
    id: 'orbe_arcano_epico',
    nome: 'Orbe Arcano Épico',
    descricao: 'Orbe epico. Para quem quer o item entre o nivel 41 e o 60.',
    tipo: 'orbe',
    uso: ['utilizacao'],
    raridade: 'epico',
    cor: 0xc9a6ff,
    textura: 'orbe',
    faixa: { min: 41, max: 60 },
    valor: 90000,
    stackMax: 999,
  },
  {
    id: 'orbe_arcano_lendario',
    nome: 'Orbe Arcano Lendário',
    descricao: 'Orbe lendario. A forma mais alta de reforco. Do nivel 61 em diante.',
    tipo: 'orbe',
    uso: ['utilizacao'],
    raridade: 'lendario',
    cor: 0xffd76a,
    textura: 'orbe',
    faixa: { min: 61, max: 999 },
    valor: 1200000,
    stackMax: 999,
  },

  // ---------- consumiveis ----------
  {
    id: 'pocao_cura',
    nome: 'Poção de Cura',
    descricao: 'Tonico de cura. Recupera 60 de Vida na hora. O limite por gole e a propria Vida maxima.',
    tipo: 'consumivel',
    uso: ['utilizacao'],
    raridade: 'comum',
    cor: 0xd05a5a,
    textura: 'consumivel',
    curaVida: 60,
    valor: 25,
    stackMax: 99,
  },
  {
    id: 'pocao_poder',
    nome: 'Elixir de Poder',
    descricao: 'Elixir de Poder. Recupera 50 de Poder imediatamente.',
    tipo: 'consumivel',
    uso: ['utilizacao'],
    raridade: 'incomum',
    cor: 0x6a5ad0,
    textura: 'consumivel',
    poderMax: 50,
    valor: 45,
    stackMax: 99,
  },
];

export const CLASSES_SEMENTE = [
  {
    id: 'guerreiro',
    nome: 'Guerreiro Imperial',
    descricao: 'Forca bruta e resistencia. Especialista em FIS e defesa.',
    nivelMin: 1,
    vidaBase: 140,
    poderBase: 70,
    fis: 12,
    men: 4,
    soc: 4,
    cor: '#d05a5a',
    bonusPorNivel: { fis: 1.2, vidaMax: 8, defesa: 1 },
  },
  {
    id: 'arcano',
    nome: 'Arcanista',
    descricao: 'Manipulação de Poder e cristais. Especialista em MEN.',
    nivelMin: 1,
    vidaBase: 100,
    poderBase: 110,
    fis: 4,
    men: 14,
    soc: 4,
    cor: '#9a6fe0',
    bonusPorNivel: { men: 1.3, poderMax: 10 },
  },
  {
    id: 'engenheiro',
    nome: 'Engenheiro Reino',
    descricao: 'Construcao, maquinas e mineracao de alto rendimento. Equilibra FIS e SOC.',
    nivelMin: 1,
    vidaBase: 120,
    poderBase: 85,
    fis: 8,
    men: 5,
    soc: 9,
    cor: '#7ab4d8',
    bonusPorNivel: { soc: 1.1, poderMineracao: 0.6 },
  },
  {
    id: 'diplomata',
    nome: 'Diplomata do Reino',
    descricao: 'Portais, comercio e lideranca. Especialista em SOC.',
    nivelMin: 1,
    vidaBase: 110,
    poderBase: 80,
    fis: 4,
    men: 8,
    soc: 14,
    cor: '#7ad4a0',
    bonusPorNivel: { soc: 1.3, ouroBonus: 8 },
  },
];

export const TALENTOS_SEMENTE = [
  // ---- Guerreiro: ramo da forca ----
  {
    id: 'g_vigor',
    nome: 'Vigor Bestial',
    classeId: 'guerreiro',
    tipo: 'passiva',
    descricao: '+18 Vida maxima por ponto.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'forca',
    posX: 0,
    posY: 0,
    preRequisitos: [],
    efeitos: { vidaMax: 18 },
  },
  {
    id: 'g_punho',
    nome: 'Punho de Ferro',
    classeId: 'guerreiro',
    tipo: 'passiva',
    descricao: '+2 FIS e +6% Poder.',
    nivelMin: 3,
    custoPontos: 1,
    ramo: 'forca',
    posX: 1,
    posY: 0,
    preRequisitos: ['g_vigor'],
    efeitos: { fis: 2, poderPct: 6 },
  },
  {
    id: 'g_espada',
    nome: 'Golpe Devastador',
    classeId: 'guerreiro',
    tipo: 'ativa',
    descricao: 'Ataque em area que causa dano dobrado no golpe critico.',
    nivelMin: 5,
    custoPontos: 2,
    custoPoder: 12,
    ramo: 'forca',
    posX: 2,
    posY: 0,
    preRequisitos: ['g_punho'],
    efeitos: { danoArea: 1, criticoPct: 12 },
  },
  {
    id: 'g_muralha',
    nome: 'Muralha de Ferro',
    classeId: 'guerreiro',
    tipo: 'passiva',
    descricao: '+9 Defesa.',
    nivelMin: 8,
    custoPontos: 2,
    ramo: 'forca',
    posX: 2,
    posY: 1,
    preRequisitos: ['g_punho'],
    efeitos: { defesa: 9 },
  },
  // ---- Guerreiro: ramo da disciplina ----
  {
    id: 'g_resolucao',
    nome: 'Resolução Marcial',
    classeId: 'guerreiro',
    tipo: 'mental',
    descricao: '+10% resistenca a dano recebido.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'disciplina',
    posX: 0,
    posY: 1,
    preRequisitos: [],
    efeitos: { reducaoDanoPct: 10 },
  },
  {
    id: 'g_combate',
    nome: 'Combate Implacavel',
    classeId: 'guerreiro',
    tipo: 'ativa',
    descricao: 'Golpes consecutivos ganham +8% de dano cada (ate 3).',
    nivelMin: 7,
    custoPontos: 2,
    custoPoder: 10,
    ramo: 'disciplina',
    posX: 1,
    posY: 1,
    preRequisitos: ['g_resolucao'],
    efeitos: { comboPct: 8, comboMax: 3 },
  },

  // ---- Arcanista: ramo da potentacao ----
  {
    id: 'a_foco',
    nome: 'Foco Arcano',
    classeId: 'arcano',
    tipo: 'passiva',
    descricao: '+8% regeneracao de Poder.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'poder',
    posX: 0,
    posY: 0,
    preRequisitos: [],
    efeitos: { regenPoderPct: 8 },
  },
  {
    id: 'a_mento',
    nome: 'Mente Expandida',
    classeId: 'arcano',
    tipo: 'passiva',
    descricao: '+3 MEN.',
    nivelMin: 2,
    custoPontos: 1,
    ramo: 'poder',
    posX: 1,
    posY: 0,
    preRequisitos: ['a_foco'],
    efeitos: { men: 3 },
  },
  {
    id: 'a_bola',
    nome: 'Orbe Destruidor',
    classeId: 'arcano',
    tipo: 'ativa',
    descricao: 'Dispara um orbe de energia (dano 2.2x Poder).',
    nivelMin: 5,
    custoPontos: 2,
    custoPoder: 14,
    ramo: 'poder',
    posX: 2,
    posY: 0,
    preRequisitos: ['a_mento'],
    efeitos: { danoMultiplicador: 2.2 },
  },
  {
    id: 'a_barreira',
    nome: 'Barreira Rúnica',
    classeId: 'arcano',
    tipo: 'ativa',
    descricao: 'Absorve dano durante 4 segundos.',
    nivelMin: 9,
    custoPontos: 2,
    custoPoder: 22,
    ramo: 'poder',
    posX: 2,
    posY: 1,
    preRequisitos: ['a_mento'],
    efeitos: { escudoPct: 40, duracao: 4 },
  },
  // ---- Arcanista: ramo do saber ----
  {
    id: 'a_erudito',
    nome: 'Erudito Arcano',
    classeId: 'arcano',
    tipo: 'mental',
    descricao: '+10% ganho de XP.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'saber',
    posX: 0,
    posY: 1,
    preRequisitos: [],
    efeitos: { xpPct: 10 },
  },
  {
    id: 'a_catalogo',
    nome: 'Catalogo Vivo',
    classeId: 'arcano',
    tipo: 'social',
    descricao: 'Revela receitas e aumenta o valor dos itens vendidos em +12%.',
    nivelMin: 4,
    custoPontos: 2,
    ramo: 'saber',
    posX: 1,
    posY: 1,
    preRequisitos: ['a_erudito'],
    efeitos: { vendaPct: 12 },
  },

  // ---- Engenheiro: ramo da extracao ----
  {
    id: 'g_forca_mao',
    nome: 'Força de Mão',
    classeId: 'engenheiro',
    tipo: 'passiva',
    descricao: '+2 Poder de Mineracao.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'extracao',
    posX: 0,
    posY: 0,
    preRequisitos: [],
    efeitos: { poderMineracao: 2 },
  },
  {
    id: 'g_pocao_mineracao',
    nome: 'Tônico de Mineiro',
    classeId: 'engenheiro',
    tipo: 'consumivel',
    descricao: 'Consumivel: +5 de mineracao por 20s.',
    nivelMin: 3,
    custoPontos: 1,
    ramo: 'extracao',
    posX: 1,
    posY: 0,
    preRequisitos: ['g_forca_mao'],
    efeitos: { poderMineracao: 5, duracao: 20 },
  },
  {
    id: 'g_construcao_rapida',
    nome: 'Construcao Rapida',
    classeId: 'engenheiro',
    tipo: 'passiva',
    descricao: 'Blocos podem ser colocados em ate 3 blocos de distancia.',
    nivelMin: 6,
    custoPontos: 2,
    ramo: 'extracao',
    posX: 2,
    posY: 0,
    preRequisitos: ['g_pocao_mineracao'],
    efeitos: { alcanceConstrucao: 3 },
  },
  // ---- Engenheiro: ramo das maquinas ----
  {
    id: 'g_engenho',
    nome: 'Engenho',
    classeId: 'engenheiro',
    tipo: 'passiva',
    descricao: 'Maquinas produzem 25% mais rapido.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'maquinas',
    posX: 0,
    posY: 1,
    preRequisitos: [],
    efeitos: { velocidadeMaquinaPct: 25 },
  },
  {
    id: 'g_reparo',
    nome: 'Reparo Automatico',
    classeId: 'engenheiro',
    tipo: 'ativa',
    descricao: 'Consome 8 de Poder e repara um bloco completo.',
    nivelMin: 8,
    custoPontos: 2,
    custoPoder: 8,
    ramo: 'maquinas',
    posX: 1,
    posY: 1,
    preRequisitos: ['g_engenho'],
    efeitos: { reparo: 1 },
  },

  // ---- Diplomata: ramo da $$(negocio) ----
  {
    id: 'd_carisma',
    nome: 'Carisma Nobre',
    classeId: 'diplomata',
    tipo: 'social',
    descricao: '+10% de ouro em todas as vendas.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'negocio',
    posX: 0,
    posY: 0,
    preRequisitos: [],
    efeitos: { ouroBonus: 10 },
  },
  {
    id: 'd_negociante',
    nome: 'Negociante',
    classeId: 'diplomata',
    tipo: 'passiva',
    descricao: 'Vende 15% mais caro.',
    nivelMin: 3,
    custoPontos: 1,
    ramo: 'negocio',
    posX: 1,
    posY: 0,
    preRequisitos: ['d_carisma'],
    efeitos: { vendaPct: 15 },
  },
  {
    id: 'd_tributo',
    nome: 'Tributo Real',
    classeId: 'diplomata',
    tipo: 'ativa',
    descricao: 'Pede 1 Orbe Arcano Menor a cada 5 inimigos derrotados.',
    nivelMin: 7,
    custoPontos: 2,
    custoPoder: 15,
    ramo: 'negocio',
    posX: 2,
    posY: 0,
    preRequisitos: ['d_negociante'],
    efeitos: { chanceOrbe: 20 },
  },
  // ---- Diplomata: ramo da diplomacia ----
  {
    id: 'd_embaixador',
    nome: 'Embaixador',
    classeId: 'diplomata',
    tipo: 'social',
    descricao: 'Visitas a bases de amigos concedem +25% XP.',
    nivelMin: 1,
    custoPontos: 1,
    ramo: 'diplomacia',
    posX: 0,
    posY: 1,
    preRequisitos: [],
    efeitos: { xpPortalPct: 25 },
  },
  {
    id: 'd_aliança',
    nome: 'Aliança Perene',
    classeId: 'diplomata',
    tipo: 'mental',
    descricao: '+2 SOC e +20 Vida.',
    nivelMin: 5,
    custoPontos: 2,
    ramo: 'diplomacia',
    posX: 1,
    posY: 1,
    preRequisitos: ['d_embaixador'],
    efeitos: { soc: 2, vidaMax: 20 },
  },
];

export const RECEITAS_SEMENTE = [
  {
    id: 'r_pedra_reforcada',
    nome: 'Bloco Reforçado',
    estacao: 'forja',
    descricao: 'Bloco estrutural reforçado.',
    insumos: [{ itemId: 'pedra', qtd: 8 }, { itemId: 'minerio_ferro', qtd: 2 }],
    saida: [{ itemId: 'bloco_pedra_reforcada', qtd: 4 }],
    tempoMs: 2200,
    custoPoder: 0,
    nivelMin: 1,
  },
  {
    id: 'r_madeira_tratada',
    nome: 'Madeira Tratada',
    estacao: 'forja',
    insumos: [{ itemId: 'madeira', qtd: 6 }],
    saida: [{ itemId: 'bloco_madeira_tratada', qtd: 4 }],
    tempoMs: 1800,
    custoPoder: 0,
    nivelMin: 1,
  },
  {
    id: 'r_picareta_ferro',
    nome: 'Picareta de Ferro',
    estacao: 'forja',
    insumos: [{ itemId: 'minerio_ferro', qtd: 6 }, { itemId: 'madeira', qtd: 4 }],
    saida: [{ itemId: 'picareta_ferro', qtd: 1 }],
    tempoMs: 4000,
    custoPoder: 0,
    nivelMin: 2,
  },
  {
    id: 'r_vidro_arcano',
    nome: 'Vidro Arcano',
    estacao: 'prensa_arcana',
    insumos: [{ itemId: 'pedra', qtd: 6 }, { itemId: 'cristal_arcano', qtd: 1 }],
    saida: [{ itemId: 'bloco_vidro_arcano', qtd: 3 }],
    tempoMs: 5000,
    custoPoder: 15,
    nivelMin: 6,
  },
  {
    id: 'r_bloco_runico',
    nome: 'Bloco Rúnico',
    estacao: 'prensa_arcana',
    insumos: [{ itemId: 'cristal_arcano', qtd: 4 }, { itemId: 'minerio_ouro', qtd: 4 }],
    saida: [{ itemId: 'bloco_runico', qtd: 1 }],
    tempoMs: 9000,
    custoPoder: 30,
    nivelMin: 14,
  },
  {
    id: 'r_prensa',
    nome: 'Prensa Arcana',
    estacao: 'torno',
    insumos: [{ itemId: 'minerio_ferro', qtd: 20 }, { itemId: 'cristal_arcano', qtd: 6 }],
    saida: [{ itemId: 'prensa_arcana', qtd: 1 }],
    tempoMs: 12000,
    custoPoder: 25,
    nivelMin: 16,
  },
  {
    id: 'r_pocao_cura',
    nome: 'Poção de Cura',
    estacao: 'alquimia',
    insumos: [{ itemId: 'cristal_arcano', qtd: 1 }, { itemId: 'minerio_ferro', qtd: 1 }],
    saida: [{ itemId: 'pocao_cura', qtd: 3 }],
    tempoMs: 3000,
    custoPoder: 8,
    nivelMin: 5,
  },
  {
    id: 'r_pocao_poder',
    nome: 'Elixir de Poder',
    estacao: 'alquimia',
    insumos: [{ itemId: 'essencia_eterea', qtd: 1 }, { itemId: 'cristal_arcano', qtd: 2 }],
    saida: [{ itemId: 'pocao_poder', qtd: 2 }],
    tempoMs: 4500,
    custoPoder: 18,
    nivelMin: 12,
  },
  {
    id: 'r_anel_arcano',
    nome: 'Anel Arcano',
    estacao: 'prensa_arcana',
    insumos: [{ itemId: 'cristal_arcano', qtd: 5 }, { itemId: 'minerio_ouro', qtd: 8 }],
    saida: [{ itemId: 'anel_arcano', qtd: 1 }],
    tempoMs: 10000,
    custoPoder: 28,
    nivelMin: 14,
  },
];

export const MONSTROS_SEMENTE = [
  {
    id: 'm_limo',
    nome: 'Limo Errante',
    tipo: 'criatura',
    raridade: 'comum',
    faixaMin: 1,
    faixaMax: 4,
    vidaMax: 45,
    poderMax: 8,
    danoBase: 7,
    defesa: 1,
    fis: 3,
    men: 0,
    soc: 0,
    alcance: 26,
    velocidade: 40,
    comportamento: 'errante',
    xpRecompensa: 14,
    cor: 0x6fa85a,
    loot: [
      { itemId: 'terra', chance: 70, qtdMin: 1, qtdMax: 3 },
      { itemId: 'pocao_cura', chance: 8, qtdMin: 1, qtdMax: 1 },
    ],
  },
  {
    id: 'm_lobo',
    nome: 'Lobo da Charneca',
    tipo: 'criatura',
    raridade: 'comum',
    faixaMin: 2,
    faixaMax: 6,
    vidaMax: 70,
    poderMax: 14,
    danoBase: 12,
    defesa: 3,
    fis: 8,
    men: 0,
    soc: 0,
    alcance: 30,
    velocidade: 85,
    comportamento: 'agressivo',
    xpRecompensa: 28,
    cor: 0x8a8a7a,
    loot: [
      { itemId: 'terra', chance: 40, qtdMin: 1, qtdMax: 2 },
      { itemId: 'pocao_cura', chance: 12, qtdMin: 1, qtdMax: 2 },
    ],
  },
  {
    id: 'm_golem',
    nome: 'Golem de Pedra',
    tipo: 'constructo',
    raridade: 'incomum',
    faixaMin: 5,
    faixaMax: 12,
    vidaMax: 220,
    poderMax: 32,
    danoBase: 26,
    defesa: 16,
    fis: 20,
    men: 0,
    soc: 0,
    alcance: 34,
    velocidade: 32,
    comportamento: 'territorial',
    xpRecompensa: 85,
    cor: 0x8a8a8a,
    loot: [
      { itemId: 'pedra', chance: 80, qtdMin: 2, qtdMax: 6 },
      { itemId: 'minerio_ferro', chance: 55, qtdMin: 1, qtdMax: 3 },
      { itemId: 'orbe_arcano_menor', chance: 10, qtdMin: 1, qtdMax: 1 },
    ],
  },
  {
    id: 'm_espectro',
    nome: 'Espectro Arcano',
    tipo: 'espirito',
    raridade: 'raro',
    faixaMin: 8,
    faixaMax: 18,
    vidaMax: 160,
    poderMax: 55,
    danoBase: 34,
    defesa: 8,
    fis: 4,
    men: 22,
    soc: 0,
    alcance: 40,
    velocidade: 70,
    comportamento: 'agressivo',
    xpRecompensa: 140,
    cor: 0x9a6fe0,
    loot: [
      { itemId: 'cristal_arcano', chance: 45, qtdMin: 1, qtdMax: 2 },
      { itemId: 'orbe_arcano_medio', chance: 8, qtdMin: 1, qtdMax: 1 },
    ],
  },
  {
    id: 'm_sentinela',
    nome: 'Sentinela Rúnica',
    tipo: 'constructo',
    raridade: 'epico',
    faixaMin: 14,
    faixaMax: 28,
    vidaMax: 480,
    poderMax: 95,
    danoBase: 62,
    defesa: 34,
    fis: 24,
    men: 30,
    soc: 0,
    alcance: 44,
    velocidade: 45,
    comportamento: 'territorial',
    xpRecompensa: 320,
    cor: 0xc9a6ff,
    loot: [
      { itemId: 'essencia_eterea', chance: 40, qtdMin: 1, qtdMax: 2 },
      { itemId: 'cristal_arcano', chance: 60, qtdMin: 2, qtdMax: 5 },
      { itemId: 'orbe_arcano_superior', chance: 6, qtdMin: 1, qtdMax: 1 },
    ],
  },
  {
    id: 'm_leviata',
    nome: 'Leviatã Etéreo',
    tipo: 'abismo',
    raridade: 'lendario',
    faixaMin: 22,
    faixaMax: 40,
    vidaMax: 1400,
    poderMax: 220,
    danoBase: 110,
    defesa: 52,
    fis: 40,
    men: 40,
    soc: 10,
    alcance: 60,
    velocidade: 58,
    comportamento: 'agressivo',
    xpRecompensa: 1400,
    cor: 0x6fd8e0,
    loot: [
      { itemId: 'essencia_eterea', chance: 90, qtdMin: 3, qtdMax: 8 },
      { itemId: 'orbe_arcano_epico', chance: 15, qtdMin: 1, qtdMax: 2 },
      { itemId: 'orbe_arcano_lendario', chance: 3, qtdMin: 1, qtdMax: 1 },
    ],
  },
];

export const REINOS_SEMENTE = [
  {
    id: 'r_campinas',
    nome: 'Campinas do Reino',
    bioma: 'campo',
    descricao: 'Planicies verdes e ruins antigas. Safe-kingdom para iniciantes.',
    dificuldade: 1,
    faixaMin: 1,
    faixaMax: 10,
    seedBase: 'campinas-01',
    cor: 0x4a7a3a,
    recursosAbundantes: ['terra', 'madeira', 'pedra'],
    monstrosPossiveis: ['m_limo', 'm_lobo'],
    lootGlobal: [{ itemId: 'minerio_ferro', chance: 18, qtdMin: 1, qtdMax: 2 }],
  },
  {
    id: 'r_garimpos',
    nome: 'Garimpos Profundos',
    bioma: 'caverna',
    descricao: 'Minas abandonadas. Ouro e monstros de pedra.',
    dificuldade: 2,
    faixaMin: 5,
    faixaMax: 16,
    seedBase: 'garimpos-01',
    cor: 0x5a4a3a,
    recursosAbundantes: ['pedra', 'minerio_ferro', 'minerio_ouro'],
    monstrosPossiveis: ['m_golem', 'm_lobo'],
    lootGlobal: [{ itemId: 'minerio_ouro', chance: 22, qtdMin: 1, qtdMax: 3 }],
  },
  {
    id: 'r_cristalinos',
    nome: 'Campos Cristalinos',
    bioma: 'etereo',
    descricao: 'Cristais que cantam. Fonte de Poder e de Orbes.',
    dificuldade: 3,
    faixaMin: 8,
    faixaMax: 24,
    seedBase: 'cristalinos-01',
    cor: 0x4a3a7a,
    recursosAbundantes: ['cristal_arcano', 'pedra'],
    monstrosPossiveis: ['m_espectro', 'm_golem'],
    lootGlobal: [{ itemId: 'orbe_arcano_medio', chance: 6, qtdMin: 1, qtdMax: 1 }],
  },
  {
    id: 'r_abismo',
    nome: 'Abismo Etéreo',
    bioma: 'vazio',
    descricao: 'Fenda entre mundos. Leviataes e Essencia Eterea.',
    dificuldade: 5,
    faixaMin: 18,
    faixaMax: 60,
    seedBase: 'abismo-01',
    cor: 0x2a1a3a,
    recursosAbundantes: ['essencia_eterea', 'cristal_arcano'],
    monstrosPossiveis: ['m_sentinela', 'm_leviata'],
    lootGlobal: [{ itemId: 'orbe_arcano_epico', chance: 4, qtdMin: 1, qtdMax: 1 }],
  },
];

export const CONQUISTAS_SEMENTE = [
  {
    id: 'c_primeiro_portal',
    nome: 'Primeiro Portal',
    descricao: 'Atravesse um Portal Arcano.',
    tipo: 'exploracao',
    chave: 'stats.portaisUsados',
    meta: 1,
    recompensaXp: 120,
    recompensaOuro: 60,
    recompensaOrbes: [{ tipo: 'orbe_arcano_menor', qtd: 2 }],
  },
  {
    id: 'c_construtor',
    nome: 'Construtor',
    descricao: 'Coloque 50 blocos em sua base.',
    tipo: 'construcao',
    chave: 'stats.blocosColocados',
    meta: 50,
    recompensaXp: 300,
    recompensaOuro: 200,
    recompensaOrbes: [{ tipo: 'orbe_arcano_menor', qtd: 3 }],
  },
  {
    id: 'c_escavador',
    nome: 'Escavador',
    descricao: 'Colete 200 blocos do mundo.',
    tipo: 'coleta',
    chave: 'stats.blocosColetados',
    meta: 200,
    recompensaXp: 320,
    recompensaOuro: 180,
    recompensaOrbes: [{ tipo: 'orbe_arcano_menor', qtd: 3 }],
  },
  {
    id: 'c_cacador',
    nome: 'Cacador de Feras',
    descricao: 'Derrote 25 monstros.',
    tipo: 'combate',
    chave: 'stats.inimigosDerrotados',
    meta: 25,
    recompensaXp: 450,
    recompensaOuro: 300,
    recompensaOrbes: [{ tipo: 'orbe_arcano_medio', qtd: 2 }],
  },
  {
    id: 'c_nivel_10',
    nome: 'Ascendente',
    descricao: 'Alcance o nivel 10.',
    tipo: 'ascensao',
    chave: 'nivel',
    meta: 10,
    recompensaXp: 0,
    recompensaOuro: 600,
    recompensaOrbes: [{ tipo: 'orbe_arcano_medio', qtd: 5 }],
  },
  {
    id: 'c_nivel_25',
    nome: 'Imperador',
    descricao: 'Alcance o nivel 25.',
    tipo: 'ascensao',
    chave: 'nivel',
    meta: 25,
    recompensaXp: 0,
    recompensaOuro: 4000,
    recompensaOrbes: [{ tipo: 'orbe_arcano_superior', qtd: 5 }],
  },
  {
    id: 'c_social',
    nome: 'Diplomacia Imperial',
    descricao: 'Visite 3 bases de amigos.',
    tipo: 'social',
    chave: 'stats.portaisUsados',
    meta: 3,
    recompensaXp: 400,
    recompensaOuro: 350,
    recompensaOrbes: [{ tipo: 'orbe_arcano_medio', qtd: 3 }],
  },
];

export const SEMENTE = {
  itens: ITENS_SEMENTE,
  classes: CLASSES_SEMENTE,
  skills: TALENTOS_SEMENTE,
  recipes: RECEITAS_SEMENTE,
  monsters: MONSTROS_SEMENTE,
  worldTemplates: REINOS_SEMENTE,
  achievements: CONQUISTAS_SEMENTE,
};
